title: Raleigh Beach
author: Hugh Janz
email: info@raleighbeach.org
description: > # this means to ignore newlines until "twitter_username:"

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
      
#disqus:
#  shortname:

google_analytics: true
google:
 analytics: UA-123247204-1
 optimize: GTM-53W7QV4

# social links
twitter_username: raleigh_beach
# github_username:
# rss: rss
# dribbble_username:
facebook_username: surfraleighbeach
# flickr_username:
instagram_username: raleigh_beach
# linkedin_username:
# pinterest_username:
# youtube_username:
# googleplus_username:

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com




show_excerpts: false # set to true to show excerpts on the homepage

date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - semantic
  - package.json
  - node_modules
  - gulpfile.js
